# Generated by Django 4.1.3 on 2022-11-27 11:28

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypost",
            name="picture",
            field=core.models.CustomModelImageField(
                blank=True, null=True, upload_to="post_pics"
            ),
        ),
    ]
