# Generated by Django 4.1 on 2022-08-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_basetextmodel_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypost",
            name="picture",
            field=models.ImageField(blank=True, upload_to="post_pics"),
        ),
    ]
