# Generated by Django 4.1 on 2022-09-07 04:42

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_basetextmodel_likes_basetextmodel_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mypost",
            name="picture",
            field=core.models.CustomModelImageField(blank=True, upload_to="post_pics"),
        ),
    ]
