# Generated by Django 4.1 on 2022-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_secret",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
