# Generated by Django 4.1 on 2022-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_email_secret_user_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("kakao", "Kakao"),
                    ("discord", "Discord"),
                ],
                default="email",
                max_length=7,
            ),
        ),
    ]
