# Generated by Django 4.1 on 2022-08-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseitem",
            name="icon",
            field=models.ImageField(upload_to="uploads/icons"),
        ),
    ]
