# Generated by Django 4.1 on 2022-08-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbages", "0002_alter_baseitem_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garbage",
            name="replacements",
            field=models.ManyToManyField(
                blank=True, related_name="garbages", to="garbages.replacement"
            ),
        ),
    ]
