# Generated by Django 4.1 on 2022-08-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garbages", "0003_alter_garbage_replacements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseitem",
            old_name="discription",
            new_name="description",
        ),
    ]
