# Generated by Django 4.1 on 2022-08-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbages", "0004_rename_discription_baseitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseitem",
            name="icon",
            field=models.ImageField(upload_to="icons"),
        ),
    ]
