# Generated by Django 4.1 on 2022-09-07 04:42

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garbages", "0005_alter_baseitem_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseitem",
            name="icon",
            field=core.models.CustomModelImageField(upload_to="icons"),
        ),
    ]
