# Generated by Django 4.1 on 2022-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="memo",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
