# Generated by Django 4.1 on 2022-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0002_history_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="memo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
