# Generated by Django 4.1 on 2022-08-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garbages", "0004_rename_discription_baseitem_description"),
        ("histories", "0003_alter_history_memo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Log",
        ),
    ]
