# Generated by Django 4.1 on 2022-08-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0005_alter_log_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="histories.history",
            ),
        ),
    ]
